### ISSUE TITLE
mariadb_configuration provider should notify restarts to the mysqld service

### ISSUE THREAD

**Issue by jwmarshall** [sous-chefs/mariadb#117]
Maybe there is a good reason why this doesn't already? A good example of this, besides when you're dropping in custom configuration files, is the `30-replication.conf` that is created after the server is installed but since the server is never restarted so `server_id` never takes affect causing issues with master/slave creation.

**Comment by shoekstra** [comment]
I understand the reason there are no notifications to restart the service is because you won't want to end up in a position where by some chance all of your cluster nodes are restarted at the same time, meaning quorum is gone and cluster members cannot start.

I imagine the idea was to manage the configuration using Chef but to have a more hands on way of restarting the services, either hand by or using some orchestrator like Ansible.

To fix your use case we can create an attribute to allow restarting if so wished.  It should default to false and be documented on the README but at least it will provide a way to let template changes notify the service to restart.

An alternate idea is to update the template, not notify the service but instead update server state using the `mysql` command and piping commands.

Thoughts?
