### ISSUE TITLE
Disable replication log

### ISSUE THREAD

**Issue by alappe** [sous-chefs/mariadb#124]
Aloha,

am I overlooking a (simple) way to disable the replication log? One approach would be to delete the generated config after the `include_recipe 'mariadb::server`, and then reload it, but I think that the whole replication log could be optional by config, couldn't it?

**Comment by kierandelaney** [comment]
Hi, looking to do the same.

The commit that references this issue should reference a pull request with the same number, it doesn't relate to this issue at all.

**Comment by kierandelaney** [comment]
Hi, looking to do the same!

The commit that references this issue should reference a pull request with the same number, it **doesn't relate to this issue** at all.

Also, just to add a bit more background - the `skip_log_bin` attribute has no effect due to the way the replication is enabled on the command line. The closest we've got is maintaining a single day with `default['mariadb']['replication']['expire_logs_days'] = '1'`

Then, to truncate the existing logs (ours were very noisy) execute the following SQL against the server: 
`RESET MASTER`

**Comment by alexandrezia** [comment]
I'm disabling replication log this way:

```
node.override['mariadb']['replication']['log_bin'] = false
node.override['mariadb']['replication']['server_id'] = nil
node.override['mariadb']['replication']['options'] = nil

include_recipe "mariadb::server"

```

**Comment by craffop** [comment]
in Version 2.0 I updated 

```
property :replication_log_bin,            String     default: lazy { "#{mysqld_log_directory}/mariadb-bin" }
```
to 
```
property :replication_log_bin,            [String, nil],     default: lazy { "#{mysqld_log_directory}/mariadb-bin" }
```
and then in my wrapper recipe just set it to nil.  have not yet tested the other way but it does at least it turns it off, with minimum changes.

**Comment by sinfomicien** [comment]
@craffop : possible to you to submit a PR please ? It will be awesome 🥇
