### ISSUE TITLE
Password management in mariadb_server_install is not working

### ISSUE THREAD

**Issue by sinfomicien** [sous-chefs/mariadb#214]
When running the resource mariadd_server_install for the first time... A password is generated. But then, it's not saved. So at the next run, when it tries to re-generate one... And don't have the old one, convergence fail.

To be able to use this feature... Either we choose to create a .my.cnf, either we disable it. Don't see any easy workaround, as it's not like postgresql.

**Comment by sinfomicien** [comment]
It's linked to #8

**Comment by PowerSchill** [comment]
I am encountering this same issue and would be interested in resolving but I am not a database person so I don't know what the best way to resolve is.

**Comment by t0rrant** [comment]
This also happens when you provide a `password` argument to `mariadb_server_install`, i.e:

```
mariadb_server_install 'MariaDB Server install' do
  password node['mariadb']['server_root_password']
  action [:install, :create]
end
```

Where after trying to set up the password, which it does not, logging in as root is impossible.

It's only a warning, but it is a pointer for the solution:

`bash[generate-mariadb-root-password] action run[2019-01-23T18:30:10+00:00] WARN: only_if block for bash[generate-mariadb-root-password] returned "***************", did you mean to run a command? If so use 'only_if "*************"' in your code.`

where ************* is the password provided by node['mariadb']['server_root_password'].

The culprit for this case seems to be:

https://github.com/sous-chefs/mariadb/blob/228c05d8630ae0823a3467ad10d46e4c7414e686/resources/server_install.rb#L66

which I guess should read ` only_if { new_resource.password != 'generate' }`

**Comment by t0rrant** [comment]
And by the way, the comment on that function seems misleading according to the documentation:

https://github.com/sous-chefs/mariadb/blob/master/README.md in line 406 (can't link directly) under `mariadb_database` it says that:

` password                   String # defaults to node['mariadb']['server_root_password']  `

which from the comment doesn't look right, which says it should be node['mariadb']['password']['root'].

From the rest of the code we can see that the documentation is right, node['mariadb']['password']['root'] is not used anywhere.

**Comment by t0rrant** [comment]
The problem seems to be that the initial root password is never properly created, so we can't access de server using root with or without password.

I'm running a few tests and proposing a solution through a PR in a while, I'll refer this issue and #220 as their are related.
