### ISSUE TITLE
undefined method `ext_conf_dir' when using mariadb 2.0.0 cookbook

### ISSUE THREAD

**Issue by aalmenar** [sous-chefs/mariadb#225]
### Cookbook version
2.0.0 (Or head from github)

### Chef-client version
14.6.47

### Platform Details
Debian 9 and Debian 10

### Scenario:
When trying to set some variable not included in the list of mariadb_server_configuration:

mariadb_configuration 'extra_innodb' do
  section 'mysqld'
  option :innodb_thread_concurrency => 8,
  :innodb_commit_concurrency => 8,
  :innodb_read_io_threads => 8,
  :innodb_flush_log_at_trx_commit => 1
end

### Steps to Reproduce:
Include the scenario inside a cookbook recipe.

### Expected Result:

Create a file inside /etc/mysql/conf.d/extra_innodb.cnf with the values:

[mysqld]
innodb_thread_concurrency = 8
innodb_commit_concurrency = 8
innodb_read_io_threads = 8
innodb_flush_log_at_trx_commit = 1

### Actual Result:
An error from chef client stating:

 NoMethodError: undefined method `ext_conf_dir' for Custom resource mariadb_configuration from cookbook mariadb

**Comment by askz** [comment]
Same here. 
Is there any fix I should be aware of?

**Comment by JohnRoesler** [comment]
We're short on maintainers for mariadb at the moment, sadly. We'd welcome a PR if you wanted to take a crack at it!

**Comment by josephholsten** [comment]
@aalmenar @askz here's the first use of the `ext_conf_dir` helper: https://github.com/sous-chefs/mariadb/commit/3d1850fd48ba0d293a6a971cab7c11ddb2bebd57. 

I suspect the issue is that `resources/configuration.rb` doesn't have the line `include MariaDBCookbook::Helpers`  like [`resources/server_configuration.rb:19`](https://github.com/sous-chefs/mariadb/commit/3d1850fd48ba0d293a6a971cab7c11ddb2bebd57#diff-340673f09bfb51387491a8e314981ecbR19). Someone want to try adding the line and seeing if it works?

**Comment by sinfomicien** [comment]
Good guess @josephholsten ! My bad, i forget it while rewriting the whole cookbook for 2.0.0 version. The `ext_conf_dir` is a method of the helper, and so you need to include the helper to use that method there. Will submit a PR to correct, and add tests so that i won't forget it next time.
